name: Build Android Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout full repo so overlay/ is available
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0" # or match your Flutter SDK

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
        working-directory: overlay

      # Build debug APK
      - name: Build debug APK
        run: flutter build apk --debug
        working-directory: overlay

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: overlay/build/app/outputs/flutter-apk/app-debug.apk
